4 1 filtration and pagination
thinknetica-django-lab-05/KostyaArent pull request #35
Opened 2021-10-30 01:26 UTC by KostyaArent

Closes #23

2021-10-30 15:22 UTC, ilyuhi4 commented on roadtojun/main/models.py
> +        return "/ads/%i/" % self.id
хардкодить не очень хорошо - в случае необходимости придётся вносить изменения в большем количестве мест

2021-10-30 15:23 UTC, ilyuhi4 commented on roadtojun/main/views.py
> +    paginate_by = 2
....вывода по 5 записей на страницу...

2021-10-30 15:35 UTC, ilyuhi4 commented on roadtojun/templates/main/ad_list.html
> +      <a href="?page={{ page_obj.previous_page_number }}tag={{selected_tag}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Previous</a>
ой, зачем такая сложная логика?

2021-10-30 15:37 UTC, ilyuhi4 commented on roadtojun/main/urls.py
в задании было что-то о .../ads/?tag=luxury (вместо luxury должен быть тэг) для получения списка объявлений содержащих данный тэг.
где мы его разруливаем по маршруту?

2021-10-30 15:38 UTC, ilyuhi4 requested changes
Попрошу исправить.

2021-11-01 14:08 UTC, ilyuhi4 commented on roadtojun/main/models.py
> +        return "/ads/%i/" % self.id
А нет ли у нас каких-то дополнительных способов обратиться к некоему УРЛу??

2021-11-01 14:09 UTC, ilyuhi4 requested changes
Давай поправим. Вроде такая простая штука...как еще можно обратиться к конкретному урлу, который имеет маршрут,

2021-11-01 21:52 UTC, KostyaArent commented on roadtojun/main/models.py
> +        return "/ads/%i/" % self.id
здесь обратился так
return reverse('ad_detail', kwargs={'pk':self.pk})

2021-11-02 21:17 UTC, ilyuhi4 commented on roadtojun/main/models.py
> +        return "/ads/%i/" % self.id
Это лучше

2021-11-02 21:18 UTC, ilyuhi4 approved these changes

2021-11-02 21:21 UTC, merged