4 5 creating a nested form
thinknetica-django-lab-05/KostyaArent pull request #45
Opened 2021-11-06 17:47 UTC by KostyaArent

Closes #27

2021-11-10 22:56 UTC, ilyuhi4 commented on roadtojun/main/views.py
> +
Этот код зачем тут? :(

2021-11-10 23:04 UTC, ilyuhi4 requested changes

2021-11-10 23:04 UTC, ilyuhi4 commented on roadtojun/main/views.py
>          return context
Ты переопределил метод get_context_data, а потом оставил в этом методе только вызов родительского метода.
Зачем оставил тогда этот метод?

2021-11-20 03:34 UTC, ilyuhi4 commented on roadtojun/main/views.py
> +            image_formset.instance = self.object
инстанс можно определить сразу в 47 строчке параметром

2021-11-20 03:36 UTC, ilyuhi4 commented on roadtojun/main/views.py
> +            self.object = form.save(commit=False)
Почему ты решил, что тут не нужно производить изменения в БД?
Данные-то кроме картинки можно сохранить?

2021-11-20 03:39 UTC, ilyuhi4 commented on roadtojun/main/views.py
> +                return HttpResponseRedirect(self.get_success_url())
возвращать руками такие штуки можно, но мы же можем обратиться к родительскому методу и получить сразу много пряников!

2021-11-20 03:41 UTC, ilyuhi4 commented on roadtojun/main/views.py
> +        print(self.object.id)
Если делаешь такой дебаг, нужно чтобы он был информативным :)

2021-11-20 03:41 UTC, ilyuhi4 approved these changes

2021-11-20 10:22 UTC, KostyaArent commented on roadtojun/main/views.py
> +            self.object = form.save(commit=False)
@ilyuhi4 исходил из того, что вторая форма может оказаться невалидной

2021-11-20 10:27 UTC, merged